// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MapToolSystem.Entities
{
    [Table("App_Info")]
    public partial class App_Info
    {
        [Key]
        public int App_ID { get; set; }//
        [Required]
        [StringLength(255)]
        public string Primary_ServiceOwner { get; set; }//
        [StringLength(255)]
        public string Secondary_ServiceOwner { get; set; }//
        [Required]
        [StringLength(255)]
        public string App_Version { get; set; }//
        [Required]
        [StringLength(255)]
        public string Instance_Name { get; set; }//
        [StringLength(255)]
        public string AD_Integrated { get; set; }//
        [StringLength(255)]
        public string Citrix_hosted { get; set; }//
        [StringLength(255)]
        public string HyperDrive_Ready { get; set; }//
        [StringLength(255)]
        public string ISS_Required { get; set; }//
        [StringLength(255)]
        public string DotNet { get; set; }//
        [StringLength(255)]
        public string SSL_Certificate { get; set; }//
        [StringLength(255)]
        public string AV_Exclusions { get; set; }//
        [StringLength(255)]
        public string App_Storage { get; set; }//
        [StringLength(255)]
        public string IAM_Integrated { get; set; }//
        [StringLength(255)]
        public string App_Type { get; set; }//
        [StringLength(255)]
        public string AD_Supported_ver { get; set; }//
        [StringLength(255)]
        public string Latest_AD_Supported { get; set; }//
        [StringLength(255)]
        public string App_Environment { get; set; }//
        [StringLength(255)]
        public string CreatedDate { get; set; }//
        [StringLength(255)]
        public string CreatedBy { get; set; }//
        [StringLength(255)]
        public string EditedDate { get; set; }//
        [StringLength(255)]
        public string EditedBy { get; set; }//
        [StringLength(255)]
        public string Backup_freq { get; set; }//
        [StringLength(255)]
        public string App_Name { get; set; }//
        [StringLength(255)]
        public string ServiceNow_AppNumber { get; set; }//
        [StringLength(100)]
        public string Server_Name { get; set; }//
        [StringLength(255)]
        public string Database_Instances { get; set; }//
        [StringLength(255)]
        public string Comments { get; set; }//
        [StringLength(255)]
        public string Hours_of_Operation { get; set; }//
        [StringLength(255)]
        public string Sites { get; set; }//
        [StringLength(255)]
        public string Primary_Lead { get; set; }//
        [StringLength(255)]
        public string Secondary_Lead { get; set; }//
        [StringLength(255)]
        public string Authentication_Provider { get; set; }//
        [StringLength(255)]
        public string Vendor_Portal { get; set; }//
    }
}