// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using MapToolSystem.DAL;
using MapToolSystem.Entities;

namespace MapToolSystem.Entities
{
    [Table("Server_Info")]
    public partial class Server_Info
    {
        [Key]
        public int Server_ID { get; set; }//
        [Required]
        [StringLength(255)]
        public string Server_Name { get; set; }//
        [StringLength(255)]
        public string Serial_Number { get; set; }//
        [StringLength(255)]
        public string IP_Address { get; set; }//
        [StringLength(255)]
        public string Support_Model { get; set; }//
        [StringLength(255)]
        public string OS_Name { get; set; }//
        [StringLength(255)]
        public string Build_Date { get; set; }//
        [StringLength(255)]
        public string Maintenance_Window { get; set; }//
        [Unicode(false)]
        public string Deployment_Type { get; set; }//
        [StringLength(50)]
        public string Support_Status { get; set; }//
        [Unicode(false)]
        public string Server_Location { get; set; }//
        [Unicode(false)]
        public string DataCenter { get; set; }//
        [Unicode(false)]
        public string Manufacturer { get; set; }//
        [StringLength(255)]
        public string Model { get; set; }//
        [StringLength(255)]
        public string Server_Type { get; set; }//
        [StringLength(255)]
        [Unicode(false)]
        public string DBType { get; set; }//
        [StringLength(255)]
        [Unicode(false)]
        public string NoOfCPUs { get; set; }//
        [StringLength(255)]
        [Unicode(false)]
        public string CPUCores { get; set; }//
        [StringLength(255)]
        public string CPUSpeeds { get; set; }//
        [StringLength(255)]
        public string RAM { get; set; }//
        public string Primary_App { get; set; }//
        public string Secondary_App { get; set; }//
        public string Other_App { get; set; }//
        [StringLength(255)]
        public string App_Type { get; set; }//
        [StringLength(255)]
        public string App_Env { get; set; }//
        [StringLength(255)]
        public string Server_Env { get; set; }//
        [StringLength(255)]
        public string Site { get; set; }//
        [StringLength(255)]
        [Unicode(false)]
        public string DMZ { get; set; }//
        [StringLength(255)]
        public string Service_Owner { get; set; }//
        public string Comments { get; set; }//
        [StringLength(255)]
        public string CreatedBy { get; set; }//
        [StringLength(255)]
        public string CreatedDate { get; set; }//
        [StringLength(255)]
        public string EditedBy { get; set; }//
        [StringLength(255)]
        public string EditedDate { get; set; }//
        public string Last_Patched { get; set; }//
        public string App_Instance_Name { get; set; }//
        [StringLength(255)]
        public string Patching_Source { get; set; }//
        [StringLength(255)]
        public string Frequency { get; set; }//
        [StringLength(255)]
        public string Vendor_approved { get; set; }//
        [StringLength(255)]
        public string Patching_Team { get; set; }//
        [StringLength(255)]
        public string Preferred_Schedule_Time { get; set; }//
        [StringLength(255)]
        public string Patching_Analyst { get; set; }//
        [StringLength(255)]
        public string WorkGroup { get; set; }//
        public string Patching_Instruction { get; set; }//
        [StringLength(50)]
        public string Zabbix_Agent { get; set; }//
        [StringLength(255)]
        public string Zone { get; set; }//
        [StringLength(50)]
        public string IsAutomationAllowed { get; set; }//
        [StringLength(255)]
        public string SysAdmin_Access { get; set; }//
    }
}