// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using MapToolSystem.Entities;

namespace MapToolSystem.DAL
{
    public partial class MapToolContext : DbContext
    {
        public MapToolContext()
        {
        }

        public MapToolContext(DbContextOptions<MapToolContext> options)
            : base(options)
        {
        }

        public virtual DbSet<App_Info> App_Infos { get; set; }
        public virtual DbSet<Server_Info> Server_Infos { get; set; }
        public virtual DbSet<Retired_Server_Info> Retired_Server_Info { get; set; }
        public virtual DbSet<User_Backlog_Info> UserBacklogs { get; set; } = null!;
        public virtual DbSet<User_Permition> UserPermitions { get; set; } = null!;
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<App_Info>(entity =>
            {
                entity.HasKey(e => e.App_ID)
                    .HasName("PK__App_Info__E976DDB02DE17EDF");
            });

            modelBuilder.Entity<Server_Info>(entity =>
            {
                entity.Property(e => e.IsAutomationAllowed).IsFixedLength();

                entity.Property(e => e.Zabbix_Agent).IsFixedLength();
            });

            modelBuilder.Entity<Retired_Server_Info>(entity =>
            {
                entity.Property(e => e.IsAutomationAllowed).IsFixedLength();

                entity.Property(e => e.Zabbix_Agent).IsFixedLength();
            });

            modelBuilder.Entity<User_Backlog_Info>(entity =>
            {
                entity.HasKey(e => e.BacklogId)
                    .HasName("PK__User_Bac__264B039F083F06AB");

                entity.ToTable("User_Backlog");

                entity.Property(e => e.ActionDone)
                    .HasMaxLength(255)
                    .HasColumnName("Action_Done");

                entity.Property(e => e.ActiveStatus).HasMaxLength(255);

                entity.Property(e => e.AssignSaName)
                    .HasMaxLength(255)
                    .HasColumnName("Assign_SA_Name");

                entity.Property(e => e.DateAndTime)
                    .HasColumnType("datetime")
                    .HasColumnName("Date_AND_TIME");

                entity.Property(e => e.PermissionLevel)
                    .HasMaxLength(255)
                    .HasColumnName("Permission_Level");

                entity.Property(e => e.UserId).HasColumnName("UserID");

                entity.Property(e => e.UserName).HasMaxLength(255);
            });

            modelBuilder.Entity<User_Permition>(entity =>
            {
                entity.HasKey(e => e.UserID)
                    .HasName("PK__User_Per__1788CCAC02C43D78");

                entity.ToTable("User_Permition");

                entity.Property(e => e.UserID).HasColumnName("UserID");

                entity.Property(e => e.ActiveStatus).HasMaxLength(255);

                entity.Property(e => e.Assign_SA_Name)
                    .HasMaxLength(255)
                    .HasColumnName("Assign_SA_Name");

                entity.Property(e => e.Password).HasMaxLength(255);

                entity.Property(e => e.Permission_Level)
                    .HasMaxLength(255)
                    .HasColumnName("Permission_Level");

                entity.Property(e => e.UserName).HasMaxLength(255);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}